[[coordinate-types]]

==  Coordinate Types 


    Four types of coordinates receive special treatment by these
    conventions: latitude, longitude, vertical, and time.
    We continue to support the special role that the
    [x-]`units` and [x-]`positive` attributes
    play in the COARDS convention to identify coordinate type.
    We extend COARDS by providing explicit definitions of dimensionless
    vertical coordinates. The definitions are associated with a coordinate
    variable via the [x-]`standard_name` and
    [x-]`formula_terms` attributes. For backwards compatibility
    with COARDS use of these attributes is not required, but is strongly recommended.
  


    Because identification of a coordinate type by its units is complicated
    by requiring the use of an external software
    package [<<udunits,UDUNITS>>], we provide two optional
    methods that yield a direct identification.
    The attribute [x-]`axis` may be attached to a coordinate
    variable and given one of the values [x-]`X`, [x-]`Y`,
    [x-]`Z` or [x-]`T` which stand for a longitude,
    latitude, vertical, or time axis respectively.
    Alternatively the [x-]`standard_name` attribute may be used
    for direct identification. But note that these optional
    attributes are in addition to the required COARDS metadata.
  


    Coordinate types other than latitude, longitude, vertical, and time
    are allowed. To identify generic spatial coordinates we recommend
    that the [x-]`axis` attribute be attached to these
    coordinates and given one of the values [x-]`X`, 
    [x-]`Y` or [x-]`Z`. 
    The values [x-]`X` and [x-]`Y`
    for the axis attribute should be used to identify horizontal coordinate
    variables. If both X- and Y-axis are identified, [x-]`X-Y-up`
    should define a right-handed coordinate system, i.e. rotation from the
    positive X direction to the positive Y direction is anticlockwise if 
    viewed from above.
    We strongly recommend that coordinate
    variables be used for all coordinate types whenever they are applicable.
  


	  The methods of identifying coordinate types described in this
      section apply both to coordinate variables and to auxiliary
      coordinate variables named by the [x-]`coordinates`
      attribute (see <<coordinate-system>>).
  


    The values of a coordinate variable or auxiliary coordinate variable 
    indicate the locations of the gridpoints. The locations of the boundaries 
    between cells are indicated by bounds variables 
    (see <<cell-boundaries>>). If bounds are not provided, 
    an application might reasonably assume the gridpoints to be at the 
    centers of the cells, but we do not require that in this standard.
  



[[latitude-coordinate]]
=== Latitude Coordinate


      Variables representing latitude must always explicitly include the
      [x-]`units` attribute; there is no default value.
      The [x-]`units` attribute will be a string formatted
      as per the
      link:$$http://www.unidata.ucar.edu/software/udunits/$$[__udunits.dat__] file.
      The recommended unit of latitude
      is [x-]`degrees_north`. Also acceptable 
      are [x-]`degree_north`, [x-]`degree_N`,
      [x-]`degrees_N`, [x-]`degreeN`,
      and [x-]`degreesN`.
    

.Latitude axis
====

----

float lat(lat) ;
  lat:long_name = "latitude" ;
  lat:units = "degrees_north" ;
  lat:standard_name = "latitude" ;
      
----


====


      Application writers should note that the Udunits package does not
      recognize the directionality implied by the "north" part of the unit
      specification. It only recognizes its size, i.e., 1 degree is defined
      to be pi/180 radians. Hence, determination that a coordinate is a
      latitude type should be done via a string match between the given unit
      and one of the acceptable forms of [x-]`degrees_north`.
    


    Optionally, the latitude type may be indicated additionally by providing
    the [x-]`standard_name` attribute with the value
    [x-]`latitude`, and/or the [x-]`axis` attribute
    with the value [x-]`Y`.
    


    Coordinates of latitude with respect to a rotated pole should be given
    units of [x-]`degrees`, not [x-]`degrees_north`
    or equivalents, because applications which use the units to identify
    axes would have no means of distinguishing such an axis from real
    latitude, and might draw incorrect coastlines, for instance. 
    



[[longitude-coordinate]]
=== Longitude Coordinate


      Variables representing longitude must always explicitly include
      the [x-]`units` attribute; there is no default value.
      The units [x-]`attribute` will be a string formatted
      as per the
      link:$$http://www.unidata.ucar.edu/software/udunits/$$[__udunits.dat__] file.
      The recommended unit of longitude is
      [x-]`degrees_east`. Also acceptable
      are [x-]`degree_east`, [x-]`degree_E`,
      [x-]`degrees_E`,  [x-]`degreeE`,
      and  [x-]`degreesE`.
    

.Longitude axis
====

----

float lon(lon) ;
  lon:long_name = "longitude" ;
  lon:units = "degrees_east" ;
  lon:standard_name = "longitude" ;
      
----


====


      Application writers should note that the Udunits package has limited
      recognition of the directionality implied by the "east" part of the
      unit specification. It defines [x-]`degrees_east` to be
      pi/180 radians, and hence equivalent to [x-]`degrees_north`.
      We recommend the determination that a coordinate is a longitude type
      should be done via a string match between the given unit and one of the
      acceptable forms of [x-]`degrees_east`.
    


      Optionally, the longitude type may be indicated additionally by
      providing the [x-]`standard_name` attribute with the
      value [x-]`longitude`, and/or the [x-]`axis`
      attribute with the value [x-]`X`.
    


      Coordinates of longitude with respect to a rotated pole should be
      given units of [x-]`degrees`, not
      [x-]`degrees_east` or equivalents, because applications
      which use the units to identify axes would have no means of
      distinguishing such an axis from real longitude, and might draw
      incorrect coastlines, for instance. 
    



[[vertical-coordinate]]
=== Vertical (Height or Depth) Coordinate


      Variables representing dimensional height or depth axes must always
      explicitly include the [x-]`units` attribute; there is
      no default value.
    


      The direction of positive (i.e., the direction in which the coordinate
      values are increasing), whether up or down, cannot in all cases be
      inferred from the units. The direction of positive is useful for
      applications displaying the data. For this reason the attribute
      [x-]`positive` as defined in the COARDS standard is
      required if the vertical axis units are not a valid unit of pressure
      (a determination which can be made using the udunits routine, utScan)
      -- otherwise its inclusion is optional. The [x-]`positive`
      attribute may have the value [x-]`up` or
      [x-]`down` (case insensitive). This attribute may be
      applied to either coordinate variables or auxillary coordinate
      variables that contain vertical coordinate data.
    


      For example, if an oceanographic netCDF file encodes the depth of
      the surface as 0 and the depth of 1000 meters as 1000 then the axis
      would use attributes as follows:
      
----

axis_name:units = "meters" ; 
axis_name:positive = "down" ; 	
      
----


    


      If, on the other hand, the depth of 1000 meters were represented
      as -1000 then the value of the [x-]`positive` attribute
      would have been [x-]`up`. If the [x-]`units`
      attribute value is a valid pressure unit the default value of the
      [x-]`positive` attribute is [x-]`down`.
    


      A vertical coordinate will be identifiable by:
      
* units of pressure; or


* 
	    the presence of the positive attribute with a value of
        [x-]`up` or [x-]`down` (case insensitive).
	  


    


      Optionally, the vertical type may be indicated additionally by
      providing the [x-]`standard_name` attribute with an
      appropriate value, and/or the [x-]`axis` attribute
      with the value [x-]`Z`.
    



==== Dimensional Vertical Coordinate


	The [x-]`units` attribute for dimensional coordinates will
    be a string formatted as per the
    link:$$http://www.unidata.ucar.edu/software/udunits/$$[__udunits.dat__] file.
    The acceptable units for vertical (depth or height) coordinate variables are:
	
* 
	      units of pressure as listed in the file __udunits.dat__.
          For vertical axes the most commonly used of these include
          include [x-]`bar`, [x-]`millibar`,
          [x-]`decibar`, [x-]`atmosphere (atm)`,
          [x-]`pascal (Pa)`, and [x-]`hPa`.
	    


* 
	      units of length as listed in the file udunits.dat. For vertical axes the most commonly used of these include [x-]`meter (metre, m)`, and [x-]`kilometer (km)`.
	    


* other units listed in the file udunits.dat that may under certain circumstances reference vertical position such as units of density or temperature.


	Plural forms are also acceptable.
      



[[dimensionless-vertical-coordinate]]
==== Dimensionless Vertical Coordinate


	The [x-]`units` attribute is not required for dimensionless coordinates. For backwards compatibility with COARDS we continue to allow the [x-]`units` attribute to take one of the values: [x-]`level`, [x-]`layer`, or [x-]`sigma_level`. These values are not recognized by the Udunits package, and are considered a deprecated feature in the CF standard.
      


	For dimensionless vertical coordinates we extend the COARDS standard by making use of the [x-]`standard_name` attribute to associate a coordinate with its definition from <<dimensionless-v-coord>>. The definition provides a mapping between the dimensionless coordinate values and dimensional values that can positively and uniquely indicate the location of the data. A new attribute, [x-]`formula_terms`, is used to associate terms in the definitions with variables in a netCDF file. To maintain backwards compatibility with COARDS the use of these attributes is not required, but is strongly recommended.
      

[[atm-sigma-coord-ex]]
.Atmosphere sigma coordinate
====

----

float lev(lev) ;
  lev:long_name = "sigma at layer midpoints" ;
  lev:positive = "down" ;
  lev:standard_name = "atmosphere_sigma_coordinate" ;
  lev:formula_terms = "sigma: lev ps: PS ptop: PTOP" ;
	
----


====


	 In this example the [x-]`standard_name` value 
         [x-]`atmosphere_sigma_coordinate` identifies the following 
         definition from <<dimensionless-v-coord>> which specifies 
         how to compute pressure at gridpoint [x-]`(n,k,j,i)` where 
         [x-]`j` and [x-]`i` are horizontal indices, 
         [x-]`k` is a vertical index, and [x-]`n` is a time index:
	
----

p(n,k,j,i) = ptop + sigma(k)*(ps(n,j,i)-ptop)
	
----


      


	The [x-]`formula_terms` attribute associates the variable [x-]`lev` with the term [x-]`sigma`, the variable [x-]`PS` with the term [x-]`ps`, and the variable [x-]`PTOP` with the term [x-]`ptop`. Thus the pressure at gridpoint [x-]`(n,k,j,i)` would be calculated by
	
----

p(n,k,j,i) = PTOP + lev(k)*(PS(n,j,i)-PTOP)
	
----


      



[[time-coordinate]]
=== Time Coordinate


      Variables representing time must always explicitly include
      the [x-]`units` attribute; there is no default value.
      The [x-]`units` attribute takes a string value formatted
      as per the recommendations in the Udunits package [<<udunits,UDUNITS>>].
      The following excerpt from the Udunits documentation explains the time unit encoding by example:
      
----

	The specification:

    seconds since 1992-10-8 15:15:42.5 -6:00

indicates seconds since October 8th, 1992  at  3  hours,  15
minutes  and  42.5 seconds in the afternoon in the time zone
which is six hours to the west of Coordinated Universal Time
(i.e.  Mountain Daylight Time).  The time zone specification
can also be written without a colon using one or  two-digits
(indicating hours) or three or four digits (indicating hours
and minutes).
      
----


    


      The acceptable units for time are listed in the
      link:$$http://www.unidata.ucar.edu/software/udunits/$$[__udunits.dat__] file.
      The most commonly used of these strings (and their abbreviations)
      includes [x-]`day (d)`, [x-]`hour (hr, h)`,
      [x-]`minute (min)` and [x-]`second (sec, s)`.
      Plural forms are also acceptable. The reference time string
      (appearing after the identifier [x-]`since`) may
      include date alone; date and time; or date, time, and time zone.
      The reference time is required. A reference time in year 0 has a
      special meaning (see <<climatological-statistics>>).
    


      __Note: if the time zone is omitted the default is UTC, and if both time and time zone are omitted the default is 00:00:00 UTC.__
    


      We recommend that the unit [x-]`year` be used with caution. The Udunits package defines a [x-]`year` to be exactly 365.242198781 days (the interval between 2 successive passages of the sun through vernal equinox). __It is not a calendar year.__ Udunits includes the following definitions for years: a [x-]`common_year` is 365 days, a [x-]`leap_year` is 366 days, a [x-]`Julian_year` is 365.25 days, and a [x-]`Gregorian_year` is 365.2425 days.
    


      For similar reasons the unit [x-]`month`, which is defined in
      link:$$http://www.unidata.ucar.edu/software/udunits/$$[__udunits.dat__]
      to be exactly [x-]`year/12`, should also be used with caution.
    

.Time axis
====

----

double time(time) ;
  time:long_name = "time" ;
  time:units = "days since 1990-1-1 0:0:0" ;
      
----


====


      A time coordinate is identifiable from its units string alone. The Udunits routines [x-]`utScan()` and [x-]`utIsTime()` can be used to make this determination.
    


      Optionally, the time coordinate may be indicated additionally by providing the [x-]`standard_name` attribute with an appropriate value, and/or the [x-]`axis` attribute with the value [x-]`T`.
    



[[calendar]]
==== Calendar


	In order to calculate a new date and time given a base date, base time and a time increment one must know what calendar to use. For this purpose we recommend that the calendar be specified by the attribute [x-]`calendar` which is assigned to the time coordinate variable. The values currently defined for [x-]`calendar` are:
	[x-]`gregorian` or [x-]`standard`:: 
		Mixed Gregorian/Julian calendar as defined by Udunits. __This is the default.__
	      

[x-]`proleptic_gregorian`:: A Gregorian calendar extended to dates before 1582-10-15. That is, a year is a leap year if either (i) it is divisible by 4 but not by 100 or (ii) it is divisible by 400.

[x-]`noleap` or [x-]`365_day`:: Gregorian calendar without leap years, i.e., all years are 365 days long.

[x-]`all_leap` or [x-]`366_day`:: Gregorian calendar with every year being a leap year, i.e., all years are 366 days long.

[x-]`360_day`:: All years are 360 days divided into 30 day months.

[x-]`julian`:: Julian calendar.

[x-]`none`:: No calendar.


      


	The [x-]`calendar` attribute may be set to [x-]`none` in climate experiments that simulate a fixed time of year. The time of year is indicated by the date in the reference time of the [x-]`units` attribute. The time coordinate that might apply in a perpetual July experiment are given in the following example.
      

.Perpetual time axis
====

----

variables:
  double time(time) ;
    time:long_name = "time" ;
    time:units = "days since 1-7-15 0:0:0" ;
    time:calendar = "none" ;
data:
  time = 0., 1., 2., ...;
      
----


====

Here, all days simulate the conditions of 15th July, so it does not make sense to give them different dates. The time coordinates are interpreted as 0, 1, 2, etc. days since the start of the experiment.


	If none of the calendars defined above applies (e.g., calendars appropriate to a different paleoclimate era), a non-standard calendar can be defined. The lengths of each month are explicitly defined with the [x-]`month_lengths` attribute of the time axis: 
	[x-]`month_lengths`:: A vector of size 12, specifying the number of days in the months from January to December (in a non-leap year).


      


	If leap years are included, then two other attributes of the time axis should also be defined:
	[x-]`leap_year`:: An example of a leap year. It is assumed that all years that differ from this year by a multiple of four are also leap years. If this attribute is absent, it is assumed there are no leap years.

[x-]`leap_month`:: 
		A value in the range 1-12, specifying which month is lengthened by a day in leap years (1=January). If this attribute is not present, February (2) is assumed. This attribute is ignored if [x-]`leap_year` is not specified.
	      


      


	The [x-]`calendar` attribute is not required when a non-standard calendar is being used. It is sufficient to define the calendar using the [x-]`month_lengths` attribute, along with [x-]`leap_year`, and [x-]`leap_month` as appropriate. However, the [x-]`calendar` attribute is allowed to take non-standard values and in that case defining the non-standard calendar using the appropriate attributes is required.
      

.Paleoclimate time axis
====

----

double time(time) ;
  time:long_name = "time" ;
  time:units = "days since 1-1-1 0:0:0" ;
  time:calendar = "126 kyr B.P." ;
  time:month_lengths = 34, 31, 32, 30, 29, 27, 28, 28, 28, 32, 32, 34 ;
	
----


====


	The mixed Gregorian/Julian calendar used by Udunits is explained in the following excerpt from the udunits(3) man page:
	
----

The udunits(3) package uses a mixed Gregorian/Julian  calen-
dar  system.   Dates  prior to 1582-10-15 are assumed to use
the Julian calendar, which was introduced by  Julius  Caesar
in 46 BCE and is based on a year that is exactly 365.25 days
long.  Dates on and after 1582-10-15 are assumed to use  the
Gregorian calendar, which was introduced on that date and is
based on a year that is exactly 365.2425 days long.  (A year
is  actually  approximately 365.242198781 days long.)  Seem-
ingly strange behavior of the udunits(3) package can  result
if  a user-given time interval includes the changeover date.
For example, utCalendar() and utInvCalendar() can be used to
show that 1582-10-15 *preceded* 1582-10-14 by 9 days.
	
----


      


	Due to problems caused by the discontinuity in the default mixed Gregorian/Julian calendar, we strongly recommend that this calendar should only be used when the time coordinate does not cross the discontinuity. For time coordinates that do cross the discontinuity the [x-]`proleptic_gregorian` calendar should be used instead.
      



[[discrete-axis]]
=== Discrete Axis

The spatiotemporal coordinates described in sections 4.1-4.4 are continuous variables, and other geophysical quantities may likewise serve as continuous coordinate variables, for instance density, temperature or radiation wavelength. By contrast, for some purposes there is a need for an axis of a data variable which indicates either an ordered list or an unordered collection, and does not correspond to any continuous coordinate variable. Consequently such an axis may be called &ldquo;discrete&rdquo;. A discrete axis has a dimension but might not have a coordinate variable. Instead, there might be one or more auxiliary coordinate variables with this dimension (see preamble to section 5). Following sections define various applications of discrete axes, for instance section 6.1.1 &ldquo;Geographical regions&rdquo;, section 7.3.3 &ldquo;Statistics applying to portions of cells&rdquo;, section 9.3 &ldquo;Representation of collections of features in data variables&rdquo;.

